---
packit_instances: ["prod", "stg"]

packages:
  hello:
    specfile_path: hello.spec
  goodbye:
    specfile_path: goodbye.spec


jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-stable-x86_64
  - fedora-rawhide-x86_64

- job: copr_build
  trigger: release
  targets:
  - fedora-stable

- job: copr_build
  trigger: commit
  branch: main
  targets:
    - fedora-stable

- job: tests
  trigger: pull_request
  targets:
  - fedora-stable-x86_64
  - fedora-rawhide-x86_64

- job: propose_downstream
  trigger: release
  packit_instances: ["stg"]
  dist_git_branches:
  - fedora-all
