---
packit_instances: ["prod", "stg"]

packages:
  hello:
    specfile_path: hello.spec
    downstream_package_name: hello
    upstream_package_name: hello
    paths:
      - ./hello_world
    files_to_sync:
      - hello.spec
  goodbye:
    specfile_path: goodbye.spec
    downstream_package_name: goodbye
    upstream_package_name: goodbye
    paths:
      - ./goodbye_world
    files_to_sync:
      - goodbye.spec


jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-stable-x86_64
  - fedora-rawhide-x86_64

- job: copr_build
  trigger: release
  targets:
  - fedora-stable

- job: copr_build
  trigger: commit
  branch: main
  targets:
    - fedora-stable

- job: tests
  trigger: pull_request
  targets:
  - fedora-stable-x86_64
  - fedora-rawhide-x86_64

- job: propose_downstream
  trigger: release
  packit_instances: ["stg"]
  dist_git_branches:
  - fedora-all
